### ISSUE TITLE
Multiple entries for "Unrecognized miners"

### ISSUE THREAD

**Issue by charlespax** [hsjoberg/fork-explorer#82]
There are currently two entries for "Unrecognized miners," one with a signalling ratio of 9/9, the other with 0/1. Both entries link to the same miner page (https://taproot.watch/miner/Unrecognized%20miners). I believe there should be a single entry with a signalling ratio of 9/10.

![Screenshot from 2021-06-03 17-08-44](https://user-images.githubusercontent.com/281642/120712258-6a22d580-c48e-11eb-92aa-8133a80b6334.png)

**Comment by hsjoberg** [comment]
@charlespax Thank you for opening this issue.
This is intended behavior actually, this is because of the way the "Total share" metric work.

**Comment by charlespax** [comment]
I think I understand. Is this to differentiate between unrecognized miners who are signalling vs those who are not?

**Comment by hsjoberg** [comment]
@charlespax Yes, sorry for the short explanation.
It's to differentiate between signalling and non-signalling. Merging them will mess up the "Total share" metric, because it's looking for the latest block for each miner (including "Unrecognized miners" and determining if their hashrate should be added to the total.

I suppose we can look into changing things here for the next softfork but I don't want to make any drastic changes now for Taproot, if that makes sense. 🙂

**Comment by charlespax** [comment]
That makes complete sense. I agree; not addressing this during the taproot soft fork is a prudent decision. Thank you.
